In [1]:
import numpy as np

In [2]:
# creating array with arange function of numpy
a = np.arange(15)               #single dimensional

a = np.arange(15).reshape(3, 5) # multi dimensional

In [3]:
# size of array
a.size

15

In [4]:
# dimensions of array
a.ndim

2

In [5]:
# datatype of array
a.dtype

dtype('int32')

In [6]:
# shape of array
a.shape

(3, 5)

In [7]:
# creating array from iterator
list_b = [1,2,3,4,5,6,7,8,9]

b= np.array(list_b).reshape(3,3)

In [8]:
# creating multi- dimensional array from iterator
b = np.array([(1.5,2,3),(4,5,6)])

In [10]:
# data type can also be specified
c = np.array([ [1,2], [3,4]], dtype=complex)

In [11]:
# array of zeros
zeros = np.zeros((3,4))

In [18]:
# array of ones
ones  = np.ones( (2,3,4), dtype= np.int16)

In [14]:
# custom range
cd = np.arange(0,2,0.3)

In [17]:
# getting the required number of elements
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [19]:
a = np.array( [20,30,40,50])
b = np.arange(4)    # array(0,1,2,3)
c = a-b # output : array([20,29,38,47])

In [20]:
b**2            # output : array([0,1,4,9])
10*np.sin(a)    # output : array([9.12945251, -9.880831624, 7.4511316, -2.62374854])
a<35            # output : array([ True, True, False, False])

array([ True,  True, False, False])

In [21]:
A = np.array( [ [1,1], [0,1] ] )
B = np.array( [ [2,0], [3,4] ] )

prod1 = A*B         # elementwise product
prod2 = A@B         # matrix product
prod3 = A.dot(B)    # another matrix product

In [22]:
a = np.ones((2,3), dtype = int)
b = np.random.random((2,3))
a *= 3  # multiplies to each element
b += a  # adds to each element

In [24]:
a = np.random.random((2,3))
# output : array([[0.60366212 0.2095924  0.19627039]
#                [0.6618519  0.31927859 0.00388182]])

a.sum()

a.min()

a.max()


0.8947897276404612