In [1]:
import numpy as np

In [2]:
# creating array with arange function of numpy
a = np.arange(15)               #single dimensional

a = np.arange(15).reshape(3, 5) # multi dimensional

In [3]:
# size of array
a.size

15

In [4]:
# dimensions of array
a.ndim

2

In [5]:
# datatype of array
a.dtype

dtype('int32')

In [6]:
# shape of array
a.shape

(3, 5)

In [7]:
# creating array from iterator
list_b = [1,2,3,4,5,6,7,8,9]

b= np.array(list_b).reshape(3,3)

In [8]:
# creating multi- dimensional array from iterator
b = np.array([(1.5,2,3),(4,5,6)])

In [10]:
# data type can also be specified
c = np.array([ [1,2], [3,4]], dtype=complex)

In [11]:
# array of zeros
zeros = np.zeros((3,4))

In [18]:
# array of ones
ones  = np.ones( (2,3,4), dtype= np.int16)

In [14]:
# custom range
cd = np.arange(0,2,0.3)

In [17]:
# getting the required number of elements
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [19]:
a = np.array( [20,30,40,50])
b = np.arange(4)    # array(0,1,2,3)
c = a-b # output : array([20,29,38,47])

In [20]:
b**2            # output : array([0,1,4,9])
10*np.sin(a)    # output : array([9.12945251, -9.880831624, 7.4511316, -2.62374854])
a<35            # output : array([ True, True, False, False])

array([ True,  True, False, False])

In [21]:
A = np.array( [ [1,1], [0,1] ] )
B = np.array( [ [2,0], [3,4] ] )

prod1 = A*B         # elementwise product
prod2 = A@B         # matrix product
prod3 = A.dot(B)    # another matrix product

In [38]:
a = np.ones((2,3), dtype = int)
b = np.random.random((2,3))
a *= 3  # multiplies to each element
b += a  # adds to each element

In [39]:
a = np.random.random((2,3))
# output : array([[0.60366212 0.2095924  0.19627039]
#                [0.6618519  0.31927859 0.00388182]])

a.sum()

a.min()

a.max()


0.9619085777588103

In [60]:
rand_array = np.random.randint(1,10,(4,5))

In [62]:
print(rand_array)

[[9 7 8 6 7]
 [4 8 5 7 6]
 [5 7 2 3 7]
 [5 7 8 2 4]]


In [63]:
print(rand_array.sum())
print(rand_array.max())
print(rand_array.min())

117
9
2


In [3]:
arr_1 = np.arange(11,20).reshape(3,3)

In [4]:
print(arr_1[1])

[14 15 16]


In [6]:
arr_1

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [7]:
arr_1[1,2]

16

In [8]:
arr_2 = np.arange(1,21).reshape(4,5)

In [9]:
arr_2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [10]:
arr_2[3,3]

19

In [11]:
arr_2[2,3:5]

array([14, 15])

In [13]:
arr_2[1:4,1]

array([ 7, 12, 17])

In [17]:
arr_2.diagonal()

array([ 1,  7, 13, 19])

In [18]:
np.ceil(arr_1)
np.floor(arr_1)

array([[11., 12., 13.],
       [14., 15., 16.],
       [17., 18., 19.]])

In [20]:
# Stacking Vertically - no. of columns should be same
arr_3 = np.arange(1,7).reshape(2,3)
arr_4 = np.arange(8,14).reshape(2,3)

In [21]:
arr_3

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr_4

array([[ 8,  9, 10],
       [11, 12, 13]])

In [23]:
np.vstack((arr_4,arr_3))

array([[ 8,  9, 10],
       [11, 12, 13],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [24]:
np.hstack((arr_3,arr_4))

array([[ 1,  2,  3,  8,  9, 10],
       [ 4,  5,  6, 11, 12, 13]])

In [28]:
np.hsplit(arr_4,3)

[array([[ 8],
        [11]]),
 array([[ 9],
        [12]]),
 array([[10],
        [13]])]

In [30]:
np.vsplit(arr_4,2)

[array([[ 8,  9, 10]]), array([[11, 12, 13]])]

In [32]:
# for transpose a matrix
# arr_4.T
arr_4.transpose()

array([[ 8, 11],
       [ 9, 12],
       [10, 13]])

In [33]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
arr_6 = np.arange(1,5).reshape(2,2)

In [35]:
arr_6 @ arr_4

array([[30, 33, 36],
       [68, 75, 82]])

In [36]:
arr_6.dot(arr_4)

array([[30, 33, 36],
       [68, 75, 82]])

In [37]:
bool_array = arr_2%2==0

In [38]:
bool_array

array([[False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [39]:
arr_2[arr_2==2]

array([2])

In [40]:
arr_2[ arr_2 % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [41]:
arr_2.trace()   # for sum of diagonals of a matrix

40